# Generated by Django 3.2.24 on 2024-02-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_id', models.CharField(max_length=100)),
                ('poi_name', models.CharField(max_length=100)),
                ('poi_latitude', models.FloatField()),
                ('poi_longitude', models.FloatField()),
                ('poi_category', models.CharField(max_length=100)),
                ('poi_ratings', models.FloatField()),
            ],
        ),
    ]
