# Generated by Django 3.2.24 on 2024-02-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofinterest',
            name='poi_id',
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='external_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='internal_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='poi_ratings',
            field=models.CharField(max_length=255),
        ),
    ]
