# Generated by Django 3.2.24 on 2024-02-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poi_manager', '0002_auto_20240221_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointofinterest',
            old_name='external_id',
            new_name='poi_id',
        ),
        migrations.RemoveField(
            model_name='pointofinterest',
            name='internal_id',
        ),
    ]
